#include <stdio.h>

int main(void) {
	printf("\033[0;32mSignature:\033[0;31m\nVardas:  Lukas\nPavarde: Kavaliauskis\nKursas:  I\nGrupe:   I\n\n");

	printf("\033[0;33mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAADBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAAUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAADLBAAAAO  LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAS   O    AABFJLJFBBFNU    FAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAF                       BAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAW                      YOBAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAABU                            WSHAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAN                             SAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAU                               YAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAFJJFAAW                                  BADHJFAAAAAAAAAAA\n\
AAAAAABO                                                     UDAAAAAA\n\
AAAAAU  YLDAAAAF                                     LBAAABHW  YDAAAA\n\
AAABY YDAAJY  WN       WHAABOY           WONSY       SQ   OBAAU  JAAA\n\
AABY WBAO            YBAAAAAAAL        JAAAAAABW            WBAO  DAA\n\
AAF  HAJ             HAAAAAAAAAW      LAAAAAAAAB             SAB  QAA\n\
AAH  FAN             HAAAAAAAAAW      HAAAAAAAAAY            UAB  SAA\n\
AAB  OAB             YBAAAAAAAN        DAAAAAAAQ             HAF  JAA\n\
AAAN  NAAO     YN      YLFDHO           WJDDHQ      LW     SBAH  YAAA\n\
AAAAL   HAAAAAAAAL            YBHW YJBN            UAAAAAAAABW  UAAAA\n\
AAAAAAQ    YUUY    UY         DAB   LAAY         S     WUW    WDAAAAA\n\
AAAAAAAABLY    YNBAAABO      WAAS   YAAN      UDAAABHU     ODAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAW                        FAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAU                          BAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAL                           SAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAS                            AAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAABW                         YHAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAABLU                 WNDAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAH NBAAAAAAAAABDBBAAAAAAAAAHYOAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAL    YUOLHFDDBBDFHJNSY    SAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAABY                      DAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAJU               WNAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBDDFDDBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\033[0m\n\n\n");

	return (0);
}